plugin:
    type: protocol              # plugin type (system, gateway, interface, protocol, cloud)
#    subtype: ...               # plugin subtype (if applicable)
    version: 1.3.3              # Plugin version
    keywords: iot               # keywords, where applicable
    sh_minversion: 1.3          # minimum shNG version to use this plugin
#   sh_maxversion:              # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: true        # plugin supports multi instance
    description: 'Implementierung eines MQTT Clients'    # description (one language only, german preferred)
#   description:               # Alternative: description in multiple languages
#       de: 'Abfrage der Daten des Wetterdienstes Wunderground.com'
#       en: 'Get weather data from wunderground.com'
   documentation: https://github.com/smarthomeNG/plugins/blob/develop/mqtt/README.md        # url of wiki page
    maintainer: msinn           # Who maintains this plugin?
#   tester:                     # Who tests this plugin?


